export const PICKUP_LOCATION_SEARCH = 'PICKUP_LOCATION_SEARCH'
export const PICKUP_LOCATION_RESULT = 'PICKUP_LOCATION_RESULT'
export const PICKUP_LOCATION_SELECT = 'PICKUP_LOCATION_SELECT'

export const DESTINATION_LOCATION_SEARCH = 'DESTINATION_LOCATION_SEARCH'
export const DESTINATION_LOCATION_RESULT = 'DESTINATION_LOCATION_RESULT'
export const DESTINATION_LOCATION_SELECT = 'DESTINATION_LOCATION_SELECT'


export const DIRECTION_REQUEST = 'DIRECTION_REQUEST'
export const DIRECTION_RESULT = 'DIRECTION_RESULT'

export const PATH_REQUEST = 'PATH_REQUEST';
export const PATH_RESULT = 'PATH_RESULT';




